import pandas as pd
import ast
from jobspy.model import Location

# Read debug CSV generated by the enrichment run (pick latest timestamped debug file)
import glob
import os

matches = sorted(glob.glob('alok_personalized_debug*.csv'), key=os.path.getmtime, reverse=True)
if not matches:
    raise FileNotFoundError('No debug file matching pattern alok_personalized_debug*.csv found')

src = matches[0]
print('Using debug file:', src)
dst = 'alok_personalized.csv'
df = pd.read_csv(src)

# Best-effort normalization: coerce serialized dicts or lists into readable strings
if 'location' in df.columns:
    def _normalize_location_str(val):
        try:
            if isinstance(val, str) and val.strip().startswith('{'):
                try:
                    d = ast.literal_eval(val)
                    if isinstance(d, dict):
                        return Location(**d).display_location()
                except Exception:
                    return val
            return val
        except Exception:
            return str(val)

    df['location'] = df['location'].apply(_normalize_location_str)

for list_col in ('key_skills', 'missing_skills', 'match_reasons'):
    if list_col in df.columns:
        def _normalize_list_cell(v):
            if isinstance(v, float) and pd.isna(v):
                return None
            if isinstance(v, str) and v.strip().startswith('['):
                try:
                    parsed = ast.literal_eval(v)
                    if isinstance(parsed, (list, tuple)):
                        return ', '.join(parsed)
                except Exception:
                    return v
            if isinstance(v, (list, tuple)):
                return ', '.join(v)
            return v
        df[list_col] = df[list_col].apply(_normalize_list_cell)

cols_map = {
    'title': 'Job Title',
    'company_name': 'Company',
    'location': 'Location',
    'site': 'Site',
    'job_url': 'Job URL',
    'experience_range': 'Experience Range',
    'key_skills': 'Key Skills Extracted',
    'match_score': 'Match Score',
    'why_this_job_fits': 'Why This Job Fits Alok Garg',
    'missing_skills': 'Missing Skills',
    'resume_alignment_level': 'Resume Alignment Level',
    'is_remote': 'Remote',
    'work_from_home_type': 'Work From Home Type',
}

out_df = df[list(c for c in cols_map.keys() if c in df.columns)].rename(columns=cols_map)
try:
    out_df.to_csv(dst, index=False)
    print('Wrote final output to', dst)
    print(out_df.head().to_string())
except PermissionError:
    alt = dst.replace('.csv', '_final.csv')
    out_df.to_csv(alt, index=False)
    print(f"Permission denied writing {dst}; wrote to {alt} instead")
    print(out_df.head().to_string())
